### ISSUE TITLE
RData

### ISSUE THREAD

**Issue by lejarx** [jriou/wcov#1]
Hi

Is it possible to share the RData generated by the simulation?
I understand that it's being produced by a HPC which I don't really have access too.

Thanks!

**Comment by jriou** [comment]
Hi,

Thanks for your interest! I'm out of town today, I will try to find a way
to put it somewhere tomorrow (it's a big file, probably too big for github).

Best,
Julien

**Comment by jriou** [comment]
Sorry about the delay, so the file is 800 MB so too big for github. I'm not sure where to put it, if you send me your email I can transfer it to you!

**Comment by lejarx** [comment]
Hi @jriou , appreciate your reply.

Is it possible to share it on Google Drive or cloud storage platform? I think it may benefit others as well. 

Plus I think email may not be able to accept or send such file as well.

Thanks!

**Comment by jriou** [comment]
So rather than to find a solution to store a huge file externally, I added a sample of the simulations that is sufficient to reproduce the results and the figures (sample_simulations.csv). I hope it's enough for you!

**Comment by lejarx** [comment]
Hi @jriou 

I apologize for the late reply. This is great.
